source 'https://rubygems.org'

ruby File.read('.ruby-version').strip

gem 'activerecord-enhancedsqlite3-adapter', '~> 0.8'
gem 'devise', '~> 4.9'
gem 'faker', '~> 3.4'
gem 'importmap-rails', '~> 2.0'
gem 'litestream', '~> 0.10.4'
gem 'pagy', '~> 9.0'
gem 'propshaft', '~> 0.9'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.2'
gem 'redis', '~> 5.1'
gem 'requestjs-rails', '~> 0.0.11'
gem 'rspec-rails', '~> 7.0'
gem 'ruby-lsp', '~> 0.17'
gem 'scenic', '~> 1.8'
gem 'scenic_sqlite_adapter', '~> 0.1'
gem 'sqlite3', '~> 2.0'
gem 'stimulus-rails', '~> 1.3'
gem 'turbo-rails', '~> 2.0'

group :development, :test do
  gem 'cuprite', '~> 0.15.1'
  gem 'debug'
  gem 'database_cleaner-active_record'
  gem 'dotenv-rails', '~> 3.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'hotwire-livereload', '~> 1.4'
  gem 'launchy', '~> 3.0'
  gem "rails-controller-testing", "~> 1.0"
end